Filters:
  - Type: From
    Folders:
      - Name: Important
        Keys: [dad@gmail.com, ex@gmail.com, lover@gmail.com, mum@gmail.com]
      - Name: Inbox
        Keys: [htty@gmail.com, nqt@gmail.com, ntv@gmail.com]
      - Name: Project
        Keys: [member@gmail.com, nqt@gmail.com, team@gmail.com]
      - Name: Spam
        Keys: [hack@gmail.com, qc@gmail.com]
      - Name: Work
        Keys: [htty@gmail.com, ntv@gmail.com]
  - Type: Subject
    Folders:
      - Name: Important
        Keys: [Important, Urgent]
      - Name: Inbox
        Keys: [Hello, Hi]
      - Name: Project
        Keys: [EmailSender, Project]
      - Name: Spam
        Keys: [Ad, Advertisement, Hack, QC]
      - Name: Work
        Keys: [EmailSender, Work]
  - Type: Content
    Folders:
      - Name: Important
        Keys: [email sender, important, project, work]
      - Name: Inbox
        Keys: [hello, hi, make friend]
      - Name: Project
        Keys: [email sender, project, socket, wireshark]
      - Name: Spam
        Keys: [advertisement, hack, spam]
      - Name: Work
        Keys: [DSA, mmt, network, nmlt, oop]