Filters:
  - Type: From
    Folders:
      - Name: Important
        Keys: [dad@gmail.com, ex@gmail.com, lover@gmail.com, mum@gmail.com]
      - Name: Inbox
        Keys: []
      - Name: Project
        Keys: [member@gmail.com, team@gmail.com]
      - Name: Spam
        Keys: [hack@gmail.com, qc@gmail.com]
      - Name: Work
        Keys: []
  - Type: Subject
    Folders:
      - Name: Important
        Keys: [Important, Urgent]
      - Name: Inbox
        Keys: []
      - Name: Project
        Keys: [Project]
      - Name: Spam
        Keys: [Ad, Advertisement, Hack, QC]
      - Name: Work
        Keys: [Work]
  - Type: Content
    Folders:
      - Name: Important
        Keys: [email sender, important, project, work]
      - Name: Inbox
        Keys: []
      - Name: Project
        Keys: []
      - Name: Spam
        Keys: [advertisement, hack, spam]
      - Name: Work
        Keys: []